/* Replace the code in Pages/index.js with this code */

import Head from "next/head";
import { useRef } from "react";

export default function Home() {
  const usernameRef = useRef("");
  const subjectRef = useRef("");
  const emailRef = useRef("");
  const messageRef = useRef("");

  async function submitForm(e) {
    e.preventDefault();
    // Getting the values from their useRef hooks
    let username, subject, email, message;
    username = usernameRef.current.value;
    subject = subjectRef.current.value;
    email = emailRef.current.value;
    message = messageRef.current.value;
    //Some form Validation
    if (!username || !subject || !email || !message) {
      alert("Failed: Ensure to fill all form inputs");
      return;
    }
    // Clear the form inputs after submit
    usernameRef.current.value =
      subjectRef.current.value =
      emailRef.current.value =
      messageRef.current.value =
        "";

    // Todo: Send the form  values to an api route
    const formValues = { username, subject, email, message };
    let result;
    try {
      let data = await fetch("/api/contact", {
        method: "POST",
        body: JSON.stringify(formValues),
        headers: {
          "Content-Type": "application/json",
          Accept: "application/json",
        },
      });
      result = await data.json();
    } catch (error) {
      result = { message: `Failed: ${error.message}` };
    }
    alert(result.message); // Gives the user some sort of feedback after the form has been processed
  }
  return (
    <>
      <Head>
        <title>Create Feedback Form</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="form-wrapper">
        <form action="/" onSubmit={submitForm}>
          <div className="form-inner">
            <h1>Send Me A Message</h1>
            <input type="text" placeholder="Name" required ref={usernameRef} />
            <input type="email" placeholder="Email" required ref={emailRef} />
            <input
              type="text"
              placeholder="Subject"
              required
              ref={subjectRef}
            />
            <textarea
              placeholder="Message..."
              rows="10"
              required
              ref={messageRef}
            ></textarea>
            <button type="submit" href="/">
              Submit
            </button>
          </div>
        </form>
      </div>
    </>
  );
}
